import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { useUser } from '../context/UserContext';
import Layout from '@components/Layout';
import styles from '../styles/CreatePost.module.css';
import { generateTagsFromEquipment, categorizeTags } from '../utils/gw2AutoTagger';

export default function CreatePost() {
  const router = useRouter();
  const { user } = useUser();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    thumbnail_url: '',
    image1_url: '',
    image2_url: '',
    image3_url: '',
    image4_url: '',
    image5_url: '',
  });

  // Auto-generated tags state
  const [autoGeneratedTags, setAutoGeneratedTags] = useState([]);
  const [categorizedTags, setCategorizedTags] = useState(null);
  const [generatingTags, setGeneratingTags] = useState(false);
  
  // GW2 API related state
  const [apiKey, setApiKey] = useState('');
  const [characters, setCharacters] = useState([]);
  const [selectedCharacter, setSelectedCharacter] = useState('');
  const [equipmentTabs, setEquipmentTabs] = useState([]);
  const [selectedTab, setSelectedTab] = useState('');
  const [loadingApiKey, setLoadingApiKey] = useState(false);
  const [loadingCharacters, setLoadingCharacters] = useState(false);
  const [loadingEquipment, setLoadingEquipment] = useState(false);

  // Redirect if not logged in
  if (typeof window !== 'undefined' && !user) {
    router.push('/login');
    return null;
  }

  // Fetch API key from backend on component mount
  const fetchApiKey = async () => {
    setLoadingApiKey(true);
    try {
      // Note: HttpOnly cookies can't be read by JavaScript, but browser will send them
      // Just try to fetch the API key - if user is logged in, it will work
      
      // Call backend directly with credentials
      const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8080';
      const response = await fetch(`${apiUrl}/api/v1/user/apikey`, {
        method: 'GET',
        credentials: 'include',
        headers: {
          'Content-Type': 'application/json',
        },
      });
      
      if (response.ok) {
        const data = await response.json();
        console.log('API key response:', data);
        
        // Backend returns { data: { apiKey: "..." }, success: true }
        const key = data.data?.apiKey || data.apiKey;
        
        if (key) {
          setApiKey(key);
          // Automatically fetch characters once we have the API key
          fetchCharactersWithKey(key);
        } else {
          console.log('No API key found in user profile');
        }
      } else {
        const errorData = await response.json();
        console.log('Could not fetch API key:', response.status, errorData.message);
        // Don't show error - user might just not have API key set
      }
    } catch (err) {
      console.error('Failed to fetch API key:', err);
    } finally {
      setLoadingApiKey(false);
    }
  };

  // Fetch API key on mount
  useEffect(() => {
    if (user) {
      fetchApiKey();
    }
  }, [user]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  // Fetch characters from GW2 API with provided key
  const fetchCharactersWithKey = async (key) => {
    if (!key) return;

    setLoadingCharacters(true);
    
    try {
      const response = await fetch(`https://api.guildwars2.com/v2/characters?access_token=${key}`);
      
      if (!response.ok) {
        throw new Error('Failed to fetch characters');
      }
      
      const data = await response.json();
      setCharacters(data);
      setSelectedCharacter('');
      setEquipmentTabs([]);
      setSelectedTab('');
    } catch (err) {
      console.error('Failed to fetch characters:', err);
      setCharacters([]);
    } finally {
      setLoadingCharacters(false);
    }
  };

  // Fetch equipment tabs for selected character
  const fetchEquipmentTabs = async (characterName) => {
    if (!characterName || !apiKey) return;

    setLoadingEquipment(true);
    setError('');
    
    try {
      const encodedName = encodeURIComponent(characterName);
      const response = await fetch(
        `https://api.guildwars2.com/v2/characters/${encodedName}/equipmenttabs?tabs=all&access_token=${apiKey}`
      );
      
      if (!response.ok) {
        throw new Error('Failed to fetch equipment tabs');
      }
      
      const data = await response.json();
      setEquipmentTabs(data);
      setSelectedTab('');
    } catch (err) {
      setError(err.message);
      setEquipmentTabs([]);
    } finally {
      setLoadingEquipment(false);
    }
  };

  // Handle character selection
  const handleCharacterChange = (e) => {
    const characterName = e.target.value;
    setSelectedCharacter(characterName);
    if (characterName) {
      fetchEquipmentTabs(characterName);
    } else {
      setEquipmentTabs([]);
      setSelectedTab('');
      setAutoGeneratedTags([]);
      setCategorizedTags(null);
    }
  };

  // Handle equipment tab selection and auto-generate tags
  const handleEquipmentTabChange = async (e) => {
    const tabName = e.target.value;
    setSelectedTab(tabName);
    
    if (tabName && selectedCharacter && apiKey) {
      setGeneratingTags(true);
      setError('');
      
      try {
        console.log('Generating tags for:', selectedCharacter, tabName);
        const tags = await generateTagsFromEquipment(selectedCharacter, tabName, apiKey);
        setAutoGeneratedTags(tags);
        
        // Categorize tags for preview
        const categorized = categorizeTags(tags);
        setCategorizedTags(categorized);
        
        console.log('Tags generated successfully:', tags);
      } catch (err) {
        console.error('Failed to generate tags:', err);
        setError('Failed to generate tags from equipment. Please try again.');
        setAutoGeneratedTags([]);
        setCategorizedTags(null);
      } finally {
        setGeneratingTags(false);
      }
    } else {
      setAutoGeneratedTags([]);
      setCategorizedTags(null);
    }
  };

  const validateForm = () => {
    if (!formData.title.trim()) {
      setError('Title is required');
      return false;
    }
    if (!formData.description.trim()) {
      setError('Description is required');
      return false;
    }
    if (!formData.thumbnail_url.trim()) {
      setError('At least one image URL is required');
      return false;
    }

    // Validate that tags were generated
    if (autoGeneratedTags.length === 0) {
      setError('Please select a character and equipment tab to generate tags');
      return false;
    }

    // Validate URLs if they are provided
    const urlFields = [
      'thumbnail_url',
      'image1_url',
      'image2_url',
      'image3_url',
      'image4_url',
      'image5_url',
    ];
    for (const field of urlFields) {
      if (formData[field] && !isValidUrl(formData[field])) {
        setError(`Invalid URL format for ${field.replace('_url', '')}`);
        return false;
      }
    }
    return true;
  };

  const isValidUrl = (string) => {
    try {
      new URL(string);
      return true;
    } catch (_) {
      return false;
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    if (!validateForm()) {
      return;
    }

    setLoading(true);

    try {
      // Get the selected equipment tab data - send the full tab object
      const selectedEquipment = equipmentTabs.find(tab => tab.name === selectedTab);
      
      // Use postsApi service for direct backend communication
      const { postsApi } = await import('../utils/postsApi');
      const data = await postsApi.createPost({
        title: formData.title,
        description: formData.description,
        thumbnailUrl: formData.thumbnail_url,
        image1Url: formData.image1_url,
        image2Url: formData.image2_url,
        image3Url: formData.image3_url,
        image4Url: formData.image4_url,
        image5Url: formData.image5_url,
        equipments: selectedEquipment || {}, // Send full equipment tab object
        tags: autoGeneratedTags, // Send auto-generated tags
        published: true,
      });

      // If successful, redirect to the new post
      if (data.id) {
        await router.push(`/posts/${data.id}`);

        // Clear form data after successful submission
        setFormData({
          title: '',
          description: '',
          thumbnail_url: '',
          image1_url: '',
          image2_url: '',
          image3_url: '',
          image4_url: '',
          image5_url: '',
        });
      } else {
        throw new Error('Post created but no ID returned');
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Layout
      title="Create"
      description="Share your Guild Wars 2 character's style with the community"
    >
      <div className="page-header">
        <h1 className="page-title">Create New Post</h1>
        <p className="page-description">
          Share your unique style with the Guild Wars 2 community
        </p>
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>Create New Post</h1>

        <div className={styles.formContainer}>
          {error && <div className={styles.error}>{error}</div>}

          <form onSubmit={handleSubmit} className={styles.form}>
            <div className={styles.formGroup}>
              <label htmlFor="title">Title *</label>
              <input
                type="text"
                id="title"
                name="title"
                value={formData.title}
                onChange={handleInputChange}
                maxLength={250}
                placeholder="Give your creation a name"
                required
              />
              <span className={styles.charCount}>
                {formData.title.length}/250
              </span>
            </div>

            <div className={styles.formGroup}>
              <label htmlFor="description">Description *</label>
              <textarea
                id="description"
                name="description"
                value={formData.description}
                onChange={handleInputChange}
                placeholder="Share the story behind your design..."
                rows={5}
                required
              />
            </div>

            <div className={styles.formGroup}>
              <label htmlFor="thumbnail_url">
                Main Image URL (Thumbnail) *
              </label>
              <input
                type="url"
                id="thumbnail_url"
                name="thumbnail_url"
                value={formData.thumbnail_url}
                onChange={handleInputChange}
                placeholder="https://..."
                required
              />
              <span className={styles.hint}>
                This will be the main image shown in the gallery
              </span>
            </div>

            {[1, 2, 3, 4, 5].map((num) => (
              <div className={styles.formGroup} key={num}>
                <label htmlFor={`image${num}_url`}>
                  Additional Image {num} URL
                </label>
                <input
                  type="url"
                  id={`image${num}_url`}
                  name={`image${num}_url`}
                  value={formData[`image${num}_url`]}
                  onChange={handleInputChange}
                  placeholder="https://..."
                />
              </div>
            ))}

            <div className={styles.divider}></div>

            {/* GW2 Equipment Section */}
            <div className={styles.apiSection}>
              <h3>Guild Wars 2 Equipment</h3>
              
              {loadingApiKey && (
                <div className={styles.loading}>Loading your GW2 data...</div>
              )}

              {!loadingApiKey && !apiKey && (
                <div className={styles.note}>
                  <p>
                    No GW2 API key found. Please add your API key in your profile settings to automatically fetch equipment data.
                  </p>
                </div>
              )}

              {apiKey && loadingCharacters && (
                <div className={styles.loading}>Loading characters...</div>
              )}

              {apiKey && characters.length > 0 && (
                <div className={styles.formGroup}>
                  <label htmlFor="character">Select Character</label>
                  <select
                    id="character"
                    value={selectedCharacter}
                    onChange={handleCharacterChange}
                    className={styles.select}
                  >
                    <option value="">-- Choose a character --</option>
                    {characters.map((char) => (
                      <option key={char} value={char}>
                        {char}
                      </option>
                    ))}
                  </select>
                </div>
              )}

              {loadingEquipment && (
                <div className={styles.loading}>Loading equipment tabs...</div>
              )}

              {equipmentTabs.length > 0 && (
                <div className={styles.formGroup}>
                  <label htmlFor="equipmentTab">Select Equipment Tab</label>
                  <select
                    id="equipmentTab"
                    value={selectedTab}
                    onChange={handleEquipmentTabChange}
                    className={styles.select}
                  >
                    <option value="">-- Choose an equipment tab --</option>
                    {equipmentTabs.map((tab) => (
                      <option key={tab.tab} value={tab.name}>
                        {tab.name} {tab.is_active ? '(Active)' : ''}
                      </option>
                    ))}
                  </select>
                </div>
              )}

              {generatingTags && (
                <div className={styles.loading}>
                  🔄 Generating tags from equipment...
                </div>
              )}

              {categorizedTags && (
                <div className={styles.tagsPreview}>
                  <h4>Auto-Generated Tags</h4>
                  <div className={styles.tagCategories}>
                    {categorizedTags.race && (
                      <div className={styles.tagCategory}>
                        <span className={styles.tagLabel}>Race:</span>
                        <span className={styles.tagValue}>{categorizedTags.race}</span>
                      </div>
                    )}
                    {categorizedTags.gender && (
                      <div className={styles.tagCategory}>
                        <span className={styles.tagLabel}>Gender:</span>
                        <span className={styles.tagValue}>{categorizedTags.gender}</span>
                      </div>
                    )}
                    {categorizedTags.class && (
                      <div className={styles.tagCategory}>
                        <span className={styles.tagLabel}>Class:</span>
                        <span className={styles.tagValue}>{categorizedTags.class}</span>
                      </div>
                    )}
                    {categorizedTags.colors.length > 0 && (
                      <div className={styles.tagCategory}>
                        <span className={styles.tagLabel}>Dye Colors:</span>
                        <span className={styles.tagValue}>{categorizedTags.colors.join(', ')}</span>
                      </div>
                    )}
                    {categorizedTags.sources.length > 0 && (
                      <div className={styles.tagCategory}>
                        <span className={styles.tagLabel}>Sources:</span>
                        <span className={styles.tagValue}>{categorizedTags.sources.join(', ')}</span>
                      </div>
                    )}
                    {categorizedTags.skins.length > 0 && (
                      <div className={styles.tagCategory}>
                        <span className={styles.tagLabel}>Skins ({categorizedTags.skins.length}):</span>
                        <span className={styles.tagValue}>{categorizedTags.skins.slice(0, 5).join(', ')}{categorizedTags.skins.length > 5 ? '...' : ''}</span>
                      </div>
                    )}
                  </div>
                  <p className={styles.tagCount}>
                    Total: {autoGeneratedTags.length} tags generated
                  </p>
                </div>
              )}
            </div>

            <div className={styles.note}>
              <p>
                * Required fields
                <br />
                Note: Your character's equipment details will be automatically
                fetched from your Guild Wars 2 account using your API key.
              </p>
            </div>

            <button
              type="submit"
              className={styles.submitButton}
              disabled={loading}
            >
              {loading ? 'Creating...' : 'Create Post'}
            </button>
          </form>
        </div>
      </main>
    </Layout>
  );
}
